language: php

php:
  - '7.1'

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE test;'
  
services:
  - mysql
  
before_script:
  - cp .env.travis .env
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpmd app text codesize design naming unusedcode
  - vendor/bin/phpunit --testdox --coverage-text tests

notifications:
  email:
    recipients:
      - moulik.adak@gmail.com
    on_success: always
    on_failure: always
